// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1LWXrEwmYo6svqCFK21lLGoHMQDVPSZI',
    appId: '1:943743637180:android:76542b81a4079fb12562b9',
    messagingSenderId: '943743637180',
    projectId: 'syd-flows',
    storageBucket: 'syd-flows.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa6PBdOBsOW9FgUd0KMduxmoGPYQXJc1g',
    appId: '1:943743637180:ios:05709b1ac7763bf32562b9',
    messagingSenderId: '943743637180',
    projectId: 'syd-flows',
    storageBucket: 'syd-flows.firebasestorage.app',
    androidClientId: '943743637180-mbdj68t3jau9iappk6cu20v87sltv1bk.apps.googleusercontent.com',
    iosClientId: '943743637180-1mcevucecgd67clndbnqgr0ib1eeljjl.apps.googleusercontent.com',
    iosBundleId: 'com.sydflows.sydflows',
  );
}
